### ISSUE TITLE
new zimwriterfs crash scenario

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#27]
with http://tmp.kiwix.org/wikipedia_ht_all_novid_2017-11.tar.xz

```
$ zimwriterfs --welcome=index.htm --favicon=favicon.png --language=hat --welcome=Paj_Prensipal.html --verbose  --tags="novid" --name="kiwix.wikipedia_ht_all" --withFullTextIndex --redirects="/tmp/mwoffliner/cac/wikipedia_ht/wikipedia_ht_all.redirects" --title="Wikipedya" --description="Depi Wikipedya, ansiklopedi lib" --creator="Wikipedia" --publisher="Kiwix" "/dev/shm//wikipedia_ht_all_novid_2017-11/" "/tmp/mwoffliner/out/wikipedia_ht_all_novid_2017-11.zim"
Reading redirects TSV file /tmp/mwoffliner/cac/wikipedia_ht/wikipedia_ht_all.redirects...
Visiting directory /dev/shm//wikipedia_ht_all_novid_2017-11
No steemming for language 'ht'
Indexing starting...
create directory entries
collect articles
basic_string::substr
```

**Comment by mgautierfr** [comment]
I don't have the redirect file so I'm running the command without the `--redirect` option.

zimwriterfs don't fails on `basic_string::substr`. It runs futher and start to index article.

However it fails later because it cannot find `wikipedia_ht_all_novid_2017-11/m/Gabriel_Soto1.jpg`
`Gabriel_Soto1.jpg` exists but it is a symlink to `/tmp/mwoffliner/cac/wikipedia_ht/m/9d652b62a2baf07e2baf.jpg`. Even by bind mounting `wikipedia_ht_all_novid_2017-11` in `/tmp/mwoffliner/cac/wikipedia_ht` it doesn't work because `m/9d652b62a2baf07e2baf.jpg` doesn't exist.

Can you provide a new archive with all files and the redirect file ?

However, even if I cannot finish to create the zim, it seems that I can go further than you.
With version of `zimwriterfs` are you using ?

**Comment by mgautierfr** [comment]
The redirect file you give me on irc seems wrong.

It has the format 
```
              A 
              1336.html 
              1336      
              1336_(almanak_jilyen).html

            
              A 
              1465.html 
              1465      
              1465_(almanak_jilyen).html

            
              A 
              882.html  
              882       
              882_(almanak_jilyen).html
```

And it should be something like :

```
A       Yeu.html        Yeu     Île_d'Yeu.html
A       Nord-ouest_argentin.html        Nord-ouest argentin     Nord-Ouest_argentin.html
A       Como.html       Como    Côme.html
A       Nürnberg.html   Nürnberg        Nuremberg.html
A       LANZHOU.html    LANZHOU Lanzhou.html
```

I don't know how you generate it, the (good) sample I give you has been generated by mwoffliner this day.

If I don't give the redirect file to zimwriterfs, everything is working correctly.
