### ISSUE TITLE
Some useful namespaces aren't included in Kiwix Zim files

### ISSUE THREAD

**Issue by ghost** [openzim/zimwriterfs#92]
I hope it's the correct place here too. Especially I mean the "Flexion" Namespace of Wiktionary (DE) ([Example](https://de.wiktionary.org/wiki/Flexion:laufen)).

**Comment by tim-st** [comment]
Thanks, it's now included (tested with wiktionary_de_all_novid_2019-04.zim)
Most different categories within `Flexion` namespace work, but infinitive verbs aren't parsed or displayed correct. For example `/A/Flexion:springen` will print `__SUB_LEVEL_SECTION_1__` instead of the content. But it seems all adjectives (`/A/Flexion:grün`) and participes (`/A/Flexion:springend`) in the `Flexion` namespace are correct.

**Comment by kelson42** [comment]
@tim-st Could you please open a separate ticket if something is still not working fine? Probably this belongs to the https://github.com/openzim/zim-requests repo.
